# Site settings
title: CJ Horton
description: 'I make web things.'

baseurl: ""

author:
  name: 'CJ Horton'
  email: thecjhorton@gmail.com
  twitter_username: _radditude
  github_username: radditude
  linkedin_username:  thecjhorton

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
