# Site settings
title: 'CJ Horton'
description: 'Software engineer and lifelong generalist. Automate the small stuff.'

baseurl: ""

author:
  name: 'CJ Horton'
  email: thecjhorton@gmail.com
  display_email: 'thecjhorton [at] gmail dot com'
  social:
    - title: Github
      url: https://github.com/radditude
    - title: Twitter
      url: https://twitter.com/_radditude
    - title: dev.to
      url: https://dev.to/radditude

nav:
  - title: home
    path: "/"
  - title: whoami
    path: "/whoami"
  - title: contact
    path: "/contact"

collections:
  posts:
    output: true
    permalink: /n/:title/
  # projects:
  #   order:
  #     - coveralls-multi.md
  #     - dotfiles.md
  #     - oceanic-page.md
  #     - legislately.md
  #     - flat-collab.md
  #     - jobby.md
  #     - toast-quotes.md
  #     - whats-on-netflix.md

# Build settings
destination: _site
markdown: kramdown

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
include: ['.well-known']

sass:
  sass_dir: css
  style: compressed
