# Site settings
title: "CJ Horton"
description: "Software engineer and lifelong generalist."

baseurl: ""

author:
  name: "CJ Horton"
  email: cjh@orton.dev
  display_email: "cjh [at] orton dot dev"
  social:
    - title: github
      url: https://github.com/radditude
    - title: twitter
      url: https://twitter.com/_radditude
    - title: mastodon
      url: https://hachyderm.io/@radditude
    - title: cohost
      url: https://cohost.org/radditude

nav:
  - title: home
    path: "/"
  - title: whoami
    path: "/whoami"
  # - title: writing
  #   path: "/writing"
  - title: contact
    path: "/contact"

collections:
  posts:
    output: true
    permalink: /:title/
  # projects:
  #   order:
  #     - coveralls-multi.md
  #     - dotfiles.md
  #     - oceanic-page.md
  #     - legislately.md
  #     - flat-collab.md
  #     - jobby.md
  #     - toast-quotes.md
  #     - whats-on-netflix.md

# Build settings
destination: _site
markdown: kramdown

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ["README.md", "Gemfile", "Gemfile.lock"]
include: [".well-known"]

sass:
  sass_dir: css
  style: compressed
