# Site settings
title: 'CJ Horton'
description: 'Software engineer and bit pusher. Automate the small stuff.'

baseurl: ""

author:
  name: 'CJ Horton'
  email: thecjhorton@gmail.com
  social:
    - twitter:
      title: twitter
      username: _radditude
      baseurl: https://twitter.com/
    - github:
      title: github
      username: radditude
      baseurl: https://github.com/
    - linkedin:
      title: linkedin
      username: thecjhorton
      baseurl: https://www.linkedin.com/in/
    - medium:
      title: medium
      username: radditude
      baseurl: https://medium.com/@
    - dev_to:
      title: dev.to
      username: radditude
      baseurl: https://dev.to/
    - mastodon:
      title: mastodon
      username: radditude
      baseurl: https://mastodon.social/@

# Build settings
destination: _site
markdown: kramdown

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

sass:
  sass_dir: css
  style: compressed
