# Site settings
title: Glob, A Blog
header-img: img/home-bg.png
email: clare.e.horton@gmail.com
copyright_name: radditude
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: itsradditude
github_username:  radditude
learn_profile: radditude
email_username: clare.e.horton@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
